name: Bots

on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Approve the PR
        if: steps.metadata.outputs.update-type != 'version-update:semver-major'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: | # shell
          gh pr review "${{ github.event.pull_request.html_url }}" \
            --approve \
            --body "@dependabot merge"
