name: Build Cron

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: dmg-arc-ubuntu
    permissions:
      contents: write
    steps:
      - uses: MailOnline/workflows/checkout@master
        with:
          ref: master

      - uses: MailOnline/workflows/yarn-install@master
      - run: yarn build
      - run: yarn test
        env:
          JWT_EMAIL: ${{ secrets.JWT_EMAIL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          NETWORK_CODE: ${{ secrets.NETWORK_CODE }}

      - uses: MailOnline/workflows/configure-git@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update state
        id: state
        run: | # shell
          COMMIT="$(yarn commit:state)"
          if [[ -n "$COMMIT" ]]; then
            MESSAGE="$(echo "$COMMIT" | jq -r '.commitMessage')"
            git add -A
            git commit -m "$MESSAGE"
            git push
          fi
