name: Release

on:
  push:
    branches: [master]

jobs:
  release-github:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  release-npm:
    needs: release-github
    if: needs.release-github.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Setup
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
        env:
          JWT_EMAIL: ${{ secrets.JWT_EMAIL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          NETWORK_CODE: ${{ secrets.NETWORK_CODE }}

      - name: Publish to NPM
        run: yarn npm publish
