name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
        env:
          JWT_EMAIL: ${{ secrets.JWT_EMAIL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          NETWORK_CODE: ${{ secrets.NETWORK_CODE }}
